### PR TITLE
Feature Added merge_pdfs Function and intergrating HTML iBoM Plugin

### PR DESCRIPTION
**Pull request by domleblanc94**
This function is used as apart of the generatePcbPdf to merge all the PDFs together with their name as the title of the page in the table of content  the original pdf name and allows for a neater solution than zipping up multiple pdfs. PDF Example attached.
[Mitayi-Pico-RP2040-R0.6-PCB-PDF-29102024-1.pdf](https://github.com/user-attachments/files/17569079/Mitayi-Pico-RP2040-R0.6-PCB-PDF-29102024-1.pdf)

new command ibom that runs this python plugin for kicad https://github.com/openscopeproject/InteractiveHtmlBom

### CODE REVIEW

**Review by vishnumaiea — CHANGES_REQUESTED** [review]
This is a nice addition. Even though KiCad CLI does not support merged PDFs by default, I had added a custom option `kie_single_file` to create merged PDFs. But I did not implement this.

I think we can use the new `merge_pdfs` to do this. Merging can be done in two ways; as multi-page PDF with each layer on individual page (like you have done), or as a single-page PDF with all layers overlaid with a layer visibility control.

I think the best way to address this is to convert the `kie_single_file` to a list and have two options `single_page` and `multi_page` in it. So a user can generate either or both at a time. If the list of values for `kie_single_file` is empty, or is `false`, we can generate individual files.

There is a reason why we generate the layers are individual files. When sending to a PCBA manufactuer, we do not want to send the inner copper layers to them. With individual files, it is easy to remove unwatend files from the ZIP. So we shoul keep this option.

**Review by vishnumaiea — COMMENTED** [review]
I've been thinking of adding the iBoM export feature. Thanks for contributing.

Please use 2-spaces for indentation as the rest of the code.

**Comment by domleblanc94** [comment]
> This is a nice addition. Even though KiCad CLI does not support merged PDFs by default, I had added a custom option `kie_single_file` to create merged PDFs. But I did not implement this.
> 
> I think we can use the new `merge_pdfs` to do this. Merging can be done in two ways; as multi-page PDF with each layer on individual page (like you have done), or as a single-page PDF with all layers overlaid with a layer visibility control.
> 
> I think the best way to address this is to convert the `kie_single_file` to a list and have two options `single_page` and `multi_page` in it. So a user can generate either or both at a time. If the list of values for `kie_single_file` is empty, or is `false`, we can generate individual files.
> 
> There is a reason why we generate the layers are individual files. When sending to a PCBA manufactuer, we do not want to send the inner copper layers to them. With individual files, it is easy to remove unwatend files from the ZIP. So we shoul keep this option.

Can the selection of layers to include in the PDF not be handled through the JSON setting file? But I agree it could be useful to have both options. Could it be worth adding a setting to enable/disable what is wanted?

**Comment by domleblanc94** [comment]
> I've been thinking of adding the iBoM export feature. Thanks for contributing.
> 
> Please use 2-spaces for indentation as the rest of the code.

There are still some issues with this feature that I have found, I maybe committed this a bit early and should have kept on a development branch. ~~Main issues being I can't seem to get all the CLI options to work for the iBOM and I currently cant see why(--extra-fields to display MPN and Manufacturer and --dnp-field kicad_dnp, these works in the GUI but not CLI).~~
There is a error in the command to enable the above `"--extra-data-file", pcb_file_path,` needs to be added into the command construct.


You may also want to think of a better method for finding the path for generate_interactive_bom.py and kicad Python.exe that is more generic across platforms. Might be better to make it a field in the JSON?

Further I may have also pushed a bit of a custom commit as I tend to use Text Variables to set the title block and the python script doesn't detect that.

**Comment by vishnumaiea** [comment]
> > This is a nice addition. Even though KiCad CLI does not support merged PDFs by default, I had added a custom option `kie_single_file` to create merged PDFs. But I did not implement this.
> > I think we can use the new `merge_pdfs` to do this. Merging can be done in two ways; as multi-page PDF with each layer on individual page (like you have done), or as a single-page PDF with all layers overlaid with a layer visibility control.
> > I think the best way to address this is to convert the `kie_single_file` to a list and have two options `single_page` and `multi_page` in it. So a user can generate either or both at a time. If the list of values for `kie_single_file` is empty, or is `false`, we can generate individual files.
> > There is a reason why we generate the layers are individual files. When sending to a PCBA manufactuer, we do not want to send the inner copper layers to them. With individual files, it is easy to remove unwatend files from the ZIP. So we shoul keep this option.
> 
> Can the selection of layers to include in the PDF not be handled through the JSON setting file? But I agree it could be useful to have both options. Could it be worth adding a setting to enable/disable what is wanted?

Yes, it can be added a custom list to decide which layers to be included in the merged PDF file. But I also fear this will end up in a "feature overrun". Instead, if we can keep it simple and let user take the decision manually after generating the files, that would be a better idea.

**Comment by vishnumaiea** [comment]
I cherry-picked the first three commits you made and made a few modidications. The iBoM export is now fully supported. Both the KiCad Python path and the iBoM script path can now be set using the JSON configuration. I tested this and found to be working. Please check the `main `branch now.

When I pushed all the changes back to the `main `branch, I am not able to see your profile as a contributor in the GitHub page. Are you sure you set the credentials correctly in you local repo?

**Pull request closed without merging**
